- name: Installazione e aggiornamento pacchetti di sistema
  hosts: localhost
  become: yes
  tasks:

    - name: Aggiornare il sistema
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Installare pacchetti di base
      pacman:
        name:
          - base-devel
          - git
          - unzip
          - wget
          - curl
          - nodejs
          - npm
          - redis
        state: present

    - name: Installare PHP e moduli necessari
      pacman:
        name:
          - php
          - php-gd
          - php-intl
          - php-fpm
        state: present

    - name: Abilitare l'estensione ZIP in PHP (se necessario)
      lineinfile:
        path: /etc/php/php.ini
        regexp: '^;?extension=zip'
        line: 'extension=zip'
        state: present
      notify: Riavvia PHP-FPM

    - name: Abilitare e avviare PHP-FPM
      systemd:
        name: php-fpm
        enabled: yes
        state: started

    - name: Installare Composer
      pacman:
        name: composer
        state: present

    - name: Abilitare e avviare Redis
      systemd:
        name: redis
        enabled: yes
        state: started

  handlers:
    - name: Riavvia PHP-FPM
      systemd:
        name: php-fpm
        state: restarted
